# Site settings
title: RIT Linux Users Group
email: ritlug@rit.edu
description: > # this means to ignore newlines until "baseurl:"
  Official site of the RIT Linux Users Group (RITlug). Find all
  our talks and announcements here.

url: 'http://ritlug.com'
# Build settings
markdown: kramdown

# These allow RITlug's schedule to be updated site-wide from one
# location. They will appear in pages as they are typed, so it
# is recommended that you follow the format already here when
# updating them.
ritlug-time: 4:00PM - 6:00PM
ritlug-place: GOL/70-2620
ritlug-day: Friday
