# Site settings
title: RIT Linux Users Group
title-abbrev: RITlug

email: ritlug@rit.edu
description: > # this means to ignore newlines until "baseurl:"
  Official site of the RIT Linux Users Group (RITlug). Find all
  our talks and announcements here.

url: 'https://ritlug.com'
# Build settings
markdown: kramdown
permalink: pretty # no .html extension needed/wanted
excerpt_separator: <!--more-->

# These allow RITlug's schedule to be updated site-wide from one
# location. They will appear in pages as they are typed, so it
# is recommended that you follow the format already here when
# updating them.
ritlug-time: 4:00PM - 6:00PM
ritlug-place: GOL/70-2650 (Large DB Lab)
ritlug-day: Friday
